#!/usr/bin/env node
/* Regenerates the Insightis custom kit's three index files from what is on disk.
   Run after adding, renaming or removing a component folder:

       node devart-ui/tools/build-index.mjs

   Writes (never hand-edit the generated blocks):
     insightis-kit/insightis-kit.css  — @import of core + every <Name>/<Name>.css
     insightis-kit/insightis-kit.js   — loader: core, every <Name>/<Name>.js, and with
                                        data-stories on its <script> tag, every *.stories.js
   Idempotent — safe to run from parallel sessions. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const kit = path.resolve(here, '../insightis-kit');

const dirs = fs.readdirSync(kit, { withFileTypes: true })
  .filter(d => d.isDirectory() && d.name !== 'core' && !d.name.startsWith('_'))
  .map(d => d.name)
  .sort((a, b) => a.localeCompare(b));

const has = (rel) => fs.existsSync(path.join(kit, rel));
const css = ['core/ik-core.css', ...dirs.map(n => `${n}/${n}.css`).filter(has)];
const js = ['core/ik-core.js', ...dirs.map(n => `${n}/${n}.js`).filter(has)];
const stories = dirs.map(n => `${n}/${n}.stories.js`).filter(has);

const banner = '/* GENERATED by devart-ui/tools/build-index.mjs — do not edit by hand. */\n';

fs.writeFileSync(path.join(kit, 'insightis-kit.css'),
  banner + '/* The Insightis custom kit — one stylesheet entry, like ds-bundle/styles.css. */\n' +
  css.map(f => `@import "./${f}";`).join('\n') + '\n');

fs.writeFileSync(path.join(kit, 'insightis-kit.js'), banner +
`/* The Insightis custom kit loader. Include it once, AFTER react.js and _ds_bundle.js:
     <script src="…/insightis-kit/insightis-kit.js"></script>
   It writes one synchronous <script> per component, in order, so everything is registered on
   window.InsightisKit before the page's own inline script runs. Works on file:// (no fetch).
   Add data-stories to the tag to also load every component's *.stories.js (storybook only). */
(function () {
  var me = document.currentScript;
  var base = me.src.replace(/insightis-kit\\.js(\\?.*)?$/, '');
  var files = ${JSON.stringify(js, null, 2).replace(/\n/g, '\n  ')};
  var stories = ${JSON.stringify(stories, null, 2).replace(/\n/g, '\n  ')};
  if (me.hasAttribute('data-stories')) files = files.concat(stories);
  for (var i = 0; i < files.length; i++) document.write('<script src="' + base + files[i] + '"><\\/script>');
})();
`);

console.log(`insightis-kit: ${dirs.length} components, ${css.length} css, ${js.length} js, ${stories.length} stories`);
